version: '3'
services:
  langchain-streamlit-agent:
    image: langchain-streamlit-agent:latest
    build: .
    #command: streamlit run streamlit_agent/chat_workflow.py --server.port 8051
    command: streamlit run streamlit_agent/chat_with_tools_functions_memory/chat.py --server.port 8051
    volumes:
      - ./streamlit_agent/:/app/streamlit_agent
    ports:
      - 8051:8051
    environment:
      - LANGCHAIN_TRACING_V2=true
      - LANGCHAIN_ENDPOINT=https://api.smith.langchain.com
      - LANGCHAIN_API_KEY=ls__01b19d36b8c94f279c3fccd7884efd16
      - LANGCHAIN_PROJECT=langchain-labs